name: deploy-main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install chromium dependencies
        run: sudo apt-get install -y libgbm-dev libnss3 libatk-bridge2.0-0 libgtk-3-0 libasound2t64

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm test
        env:
          MONGO_URI: mongodb://localhost:27017/musango_test
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}

      - name: build
        run: npm run build

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: log in to docker hub
        uses: docker/login-action@v3
        with:
          username: meshe41
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: meshe41/landmark-devops-app:latest,meshe41/landmark-devops-app:${{ github.sha }}
          cache-from: type=registry,ref=meshe41/landmark-devops-app:cache
          cache-to: type=registry,ref=meshe41/landmark-devops-app:cache,mode=max
